/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bandtec.projetoindividual;

/**
 *
 * @author caio-
 */
public class calculadoraFinanceira extends javax.swing.JFrame {

    /**
     * Creates new form calculadoraFinanceira
     */
    public calculadoraFinanceira() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGastoMes = new javax.swing.JLabel();
        txtfMes = new javax.swing.JTextField();
        lblGastoAno = new javax.swing.JLabel();
        txtfAno = new javax.swing.JTextField();
        lblEconomia = new javax.swing.JLabel();
        btnEconomia = new javax.swing.JButton();
        lblTitleMes = new javax.swing.JLabel();
        lblQtdLamp = new javax.swing.JLabel();
        txtfQtdLamp = new javax.swing.JTextField();
        lblQtdWatts = new javax.swing.JLabel();
        txtfQtdWatts = new javax.swing.JTextField();
        lblTitleAno = new javax.swing.JLabel();
        lblEconomiaMes = new javax.swing.JLabel();
        lblEconomiaAno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAcessasMes = new javax.swing.JLabel();
        txtfDiasMes = new javax.swing.JTextField();
        lblAcessasHoras = new javax.swing.JLabel();
        txtfHorasDias = new javax.swing.JTextField();
        lblWattsMes = new javax.swing.JLabel();
        btnWatts = new javax.swing.JButton();
        lblWatts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGastoMes.setText("Quanto sua empresa gasta com energia em um mês?");

        txtfMes.setText("Valor");
        txtfMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfMesActionPerformed(evt);
            }
        });

        lblGastoAno.setText("Quanto sua empresa gasta com energia em um ano?");

        txtfAno.setText("Valor");

        lblEconomia.setText("Clique para saber o quanto sua empresa vai economizar: ");

        btnEconomia.setText("Economia");
        btnEconomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEconomiaActionPerformed(evt);
            }
        });

        lblTitleMes.setText("Valor da economia por mês:");

        lblQtdLamp.setText("Quantas lâmpadas sua empresa possui?");

        txtfQtdLamp.setText("Quantidade");

        lblQtdWatts.setText("Quantos Watts as lâmpadas possuem?");

        txtfQtdWatts.setText("Watts");

        lblTitleAno.setText("Valor da economia por ano:");

        lblEconomiaMes.setText("0");

        lblEconomiaAno.setText("0");

        lblAcessasMes.setText("Quantos dias no mês suas lâmpadas ficam acessas?");

        txtfDiasMes.setText("Dias/Mês");

        lblAcessasHoras.setText("Quantas horas no dia suas lâmpadas ficam acessar?");

        txtfHorasDias.setText("Horas/Dia");

        lblWattsMes.setText("Clique para saber quantos Watts você utiliza por mês:");

        btnWatts.setText("Clique");
        btnWatts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWattsActionPerformed(evt);
            }
        });

        lblWatts.setText("0 Watts/mês");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblGastoAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEconomia)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGastoMes)
                    .addComponent(txtfQtdLamp, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfQtdWatts, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdWatts)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcessasHoras))
                        .addGap(388, 388, 388)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWattsMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnWatts)
                        .addGap(18, 18, 18)
                        .addComponent(lblWatts))
                    .addComponent(lblAcessasMes)
                    .addComponent(txtfHorasDias, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdLamp))
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitleAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEconomiaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitleMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEconomiaMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEconomia)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblGastoMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEconomia, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGastoAno)
                            .addComponent(btnEconomia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitleMes)
                        .addComponent(lblEconomiaMes)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdLamp)
                    .addComponent(lblTitleAno)
                    .addComponent(lblEconomiaAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfQtdLamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQtdWatts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfQtdWatts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAcessasMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAcessasHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfHorasDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWattsMes)
                            .addComponent(btnWatts)
                            .addComponent(lblWatts))
                        .addGap(0, 7, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfMesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfMesActionPerformed

    private void btnEconomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEconomiaActionPerformed
        // TODO add your handling code here:
        
        String valorMes = txtfMes.getText();
        Double mes = Double.valueOf(valorMes);
        
        String valorAno = txtfAno.getText();
        Double ano = Double.valueOf(valorAno);
        
        Double calculoMes = mes * 0.30;
        Double calculoAno = (ano * 0.30) * 12;
        
        lblEconomiaMes.setText("R$" + calculoMes);
        lblEconomiaAno.setText("R$" + calculoAno);
        
    }//GEN-LAST:event_btnEconomiaActionPerformed

    private void btnWattsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWattsActionPerformed
        // TODO add your handling code here:
        
        String qtdLamp = txtfQtdLamp.getText();
        Double qtdLampadas = Double.valueOf(qtdLamp);
        
        String qtdWatts = txtfQtdWatts.getText();
        Double qtdWattsLamp = Double.valueOf(qtdWatts);
        
        String wattsDiasMes = txtfDiasMes.getText();
        Double diasMes = Double.valueOf(wattsDiasMes);
        
        String wattsHorasDias = txtfHorasDias.getText();
        Double horasDias = Double.valueOf(wattsHorasDias);
        
        Double calculoWatts = (qtdLampadas * qtdWattsLamp) * (horasDias * diasMes) / 1000;
        
        lblWatts.setText(calculoWatts + "kWs/mês");
        
    }//GEN-LAST:event_btnWattsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadoraFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadoraFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadoraFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadoraFinanceira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadoraFinanceira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEconomia;
    private javax.swing.JButton btnWatts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAcessasHoras;
    private javax.swing.JLabel lblAcessasMes;
    private javax.swing.JLabel lblEconomia;
    private javax.swing.JLabel lblEconomiaAno;
    private javax.swing.JLabel lblEconomiaMes;
    private javax.swing.JLabel lblGastoAno;
    private javax.swing.JLabel lblGastoMes;
    private javax.swing.JLabel lblQtdLamp;
    private javax.swing.JLabel lblQtdWatts;
    private javax.swing.JLabel lblTitleAno;
    private javax.swing.JLabel lblTitleMes;
    private javax.swing.JLabel lblWatts;
    private javax.swing.JLabel lblWattsMes;
    private javax.swing.JTextField txtfAno;
    private javax.swing.JTextField txtfDiasMes;
    private javax.swing.JTextField txtfHorasDias;
    private javax.swing.JTextField txtfMes;
    private javax.swing.JTextField txtfQtdLamp;
    private javax.swing.JTextField txtfQtdWatts;
    // End of variables declaration//GEN-END:variables
}
